language: python
sudo: false
python:
  - 3.7
  - 3.8
env:
  - TASK=test
  - TASK=integration
matrix:
  include:
  - python: 3.8
    env: TASK=checks
install:
  - pip install tox-travis
script:
  - tox
